server:
  port: 8081

spring:
  application:
    name: merchant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/merchant_db
    username: pgs
    password: pgs
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
